sudo: false
language: java
branches:
  only:
  - develop
jdk:
- oraclejdk8
before_install:
- cat ~/.m2/settings.xml  
- sed -i.bak -e 's|https://nexus.codehaus.org/snapshots/|https://oss.sonatype.org/content/repositories/snapshots/|g' ~/.m2/settings.xml
