sudo: false
language: java
branches:
  only:
  - develop
jdk:
- oraclejdk8
- oraclejdk7
- openjdk7
after_success:
  - echo "<settings><servers><server><id>ossrh</id><username>\${env.OSSRH_USER}</username><password>\${env.OSSRH_PASS}</password></server></servers></settings>" > ~/settings.xml
  - '[ ${TRAVIS_PULL_REQUEST} = ''false'' ] && mvn deploy --settings ~/settings.xml || echo "SKIP DEPLOY BECAUSE IT'S A PULL REQUEST"'
