sudo: false
language: java
before_install: git clone -b travis `git config --get remote.origin.url` target/travis
script: '[ ${TRAVIS_PULL_REQUEST} = ''false'' ] && mvn clean deploy -Dorientdb.test.env=ci
  --settings target/travis/settings.xml || mvn clean verify -Dorientdb.test.env=ci
  --settings target/travis/settings.xml'
branches:
  only:
  - develop
jdk:
- oraclejdk8
- oraclejdk7
- openjdk7
env:
  global:
  - secure: H9NadRz3kBolRce6lEOBRTX7LEF4L+Nj+btL58wpExYBqKr6hKV8VayNYfuubJ2XSHhoX3rW4a51u3P8LYUGvAxAyOeVPtIKdwskXx6x49gLqVN/VWZMaEQXwm3F2TooeggHUe+0b51JxRuuSwfofxLFva0L+KJupvVCt/QjK7w=
  - secure: Gcm+x6F0WgwHxGuvkSIGRBFBZ+SiP+IDpihYb+Dr8praadpwNPi4vKhqs1hHcSOPuJ3yyp1RPT0CtrHlXg7VBEyjXxKtTYE3S87eMayuKCvtWIH8hBBG6AZZfE5QqsOSVqzhz3OkPCwy4SR5fs2dzQnmKWa0qcRUYJp5hSGG+KE=
